// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bizbwffnhlqfbjpijezq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpemJ3ZmZuaGxxZmJqcGlqZXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzA1NTksImV4cCI6MjA2MDQwNjU1OX0.gNKDoN4Ixpk8hOOsuczr1TVfmHOySQyn2cgNhxmbtLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);